repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.5.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml
          - id: check-added-large-files

    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v1.7.1
      hooks:
          - id: mypy
            additional_dependencies:
                - pydantic
                - types-toml
                - types-PyYaml==6.0.12.12
                - types-requests

    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.1.6
      hooks:
          - id: ruff
            args: [ --fix ]
          - id: ruff-format

    - repo: https://github.com/compilerla/conventional-pre-commit
      rev: v3.0.0
      hooks:
          - id: conventional-pre-commit
            stages: [ commit-msg ]

    - repo: https://github.com/python-poetry/poetry
      rev: 1.7.0
      hooks:
          - id: poetry-check
          - id: poetry-lock
